// 构建静态版数据：把 knowledge/*.md 打包成 docs/kb-data.js（window.KB_DATA）
// 用法：node scripts/build-static.js   （修改 knowledge/ 后需重跑并重新推送 docs/）
const path = require("path");
const fs = require("fs");
const kb = require("../lib/kb");

const KB_DIR = path.join(__dirname, "..", "knowledge");
const OUT = path.join(__dirname, "..", "docs", "kb-data.js");

const entries = kb.load(KB_DIR).map(e => ({
  code: e.code || "", title: e.title || "", severity: e.severity || "",
  ref: e.ref || "", keywords: e.keywords || [], body: e.body
}));

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT,
  "// AUTO-GENERATED by scripts/build-static.js — do not edit by hand\n" +
  "window.KB_DATA = " + JSON.stringify(entries, null, 1) + ";\n");
console.log("OK: " + entries.length + " entries -> " + OUT);
